Revert redeem integration test
OpenSTFoundation/openst-protocol pull request #747
Opened 2019-05-20 07:01 UTC by deepesh-kn

Fixes #610 
Revert redeem integration test.

2019-05-20 15:30 UTC, jasonklein submitted a review, later dismissed
A few comments, mostly refactoring and typographical. On refactoring, there is a fair amount of repetition (e.g., type definitions like `RedeemRequest`, functions like `proveGateway`, etc.)—can this be refactored?

Additionally, I suggest changing "unStake" and "UnStake" to "unstake" and "Unstake", respectively, globally.

Finally, when I lint, errors are raised, even in the files that are entirely new—please review and address.

2019-05-20 15:30 UTC, jasonklein commented on test_integration/03_redeem_and_unstake/utils/progress_revert_redeem_assertion.js
> +  async _getEthBalance(address) {
I think there is a risk of confusion referring to both base token and eth. In the absence of a substantive reason that outweighs that risk of confusion, I suggest renaming this to something like `_getBaseTokenBalance` or some other consistency solution.

🤓 I acknowledge that this function is defined in a few places and that the best solution may be to leave it as is here and instead make this (and other deduplication refactoring changes) in one or more other PRs.

**I'm also curious about the value of this function.** Is the below too clunky or bad practice:
```
new BN(await this.web3.eth.getBalance(<address>));
```

2019-05-27 06:04 UTC, deepesh-kn commented on test_integration/03_redeem_and_unstake/03_revert_redeem.js
> +  const proveCoGateway = async () => {
There are almost all the functions that are identical in the tests. 
Created a ticket to deduplicate the code
https://github.com/OpenST/mosaic-contracts/issues/756

2019-05-27 06:04 UTC, deepesh-kn commented on test_integration/03_redeem_and_unstake/03_revert_redeem.js
> +  const proveGateway = async () => {
Same as above.

2019-05-27 06:07 UTC, deepesh-kn commented on test_integration/03_redeem_and_unstake/utils/revert_redeem_assertion.js
> +    const expectedCoGatewayTokenBalance = initialBalances.token.cogateway;
I prefer this because it makes it more readable. I can change it if you think that it should be `initialBalances.token.cogateway`

2019-05-27 11:56 UTC, jasonklein commented on test_integration/03_redeem_and_unstake/utils/confirm_revert_redeem_intent_assertion.js
> + * @typedef {Object} RedeemRequest
I will mark this as resolved on the assumption that, if it is thought sensible, this will be addressed by #756.

2019-05-27 12:12 UTC, 0xsarvesh requested changes
Overall looks good. 
Some minor but important changes.

2019-05-27 12:12 UTC, sarvesh-ost commented on test_integration/03_redeem_and_unstake/03_revert_redeem.js
> +    event = EventDecoder.getEvents(tx, gateway);
```suggestion
    const event = EventDecoder.getEvents(tx, gateway);
```

2019-05-27 12:12 UTC, sarvesh-ost commented on test_integration/03_redeem_and_unstake/03_revert_redeem.js
> +    tx = await gateway.confirmRevertRedeemIntent(
```suggestion
  const  tx = await gateway.confirmRevertRedeemIntent(
```

2019-05-27 12:12 UTC, sarvesh-ost commented on test_integration/03_redeem_and_unstake/03_revert_redeem.js
> +    event = EventDecoder.getEvents(tx, gateway);
```suggestion
   const event = EventDecoder.getEvents(tx, gateway);
```

2019-05-27 12:12 UTC, sarvesh-ost commented on test_integration/03_redeem_and_unstake/utils/revert_redeem_assertion.js
> +    // Assert Penalty is transferred to cogateway.
😱  This message is wrong. The penalty is burned on revert redeem.

2019-05-27 12:12 UTC, sarvesh-ost commented on test_integration/03_redeem_and_unstake/utils/revert_redeem_assertion.js
> +    // Assert redeem amount is transferred to cogateway.
😱

2019-05-27 13:53 UTC, 0xsarvesh approved these changes
LGTM 🚀 ✅

2019-05-27 13:54 UTC, merged